services:
  db:
    image: postgres:17
    container_name: taskmanagement-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpassword
      POSTGRES_DB: taskmanagement
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
